### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by UTilitieeees** [jamarju/easyflash#2]
I wanted to compile EasyTransfer:

make: *** No rule to make target `3/_Tools_also_MacOS/_MacOS/easyflash-master/easyflash-master/EasyTransfer/archive/%.tar.gz', needed by `Flash'.  Stop.

**Comment by jamarju** [comment]
Do you have spaces in your pathnames? Make *hates* them.

**Comment by UTilitieeees** [comment]
Oh, yes :-)

Changed... now an other error:

Warning: No config found to match: /usr/local/bin/wx-config --static --libs


The reason is... I can't install it with "--with-static" option because of this error:
"Error: invalid option: --with-static"

**Comment by UTilitieeees** [comment]
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src/d64writer/
ca65 -t c64 -Isrc -I../../../libs/libef3usb/src -I../../../libs/eload/src -o obj/crt0.o src/crt0.s
make[1]: ca65: No such file or directory
make[1]: *** [obj/crt0.o] Error 1
make: *** [src/d64writer/d64writer.prg] Error 2

**Comment by UTilitieeees** [comment]
Ok, cc65 was not installed. 

Next Error:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src/d64writer/
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../../libs/libef3usb/
make[2]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../../libs/eload/
make[2]: Nothing to be done for `all'.
convert  src/../res/easytransfer.png /Applications/EasyFlash3/easyflash-master/EasyTransfer/out/obj/easytransfer.xpm.tmp.xpm
make: convert: No such file or directory
make: *** [/Applications/EasyFlash3/_Tools_also_MacOS/easyflash-master/EasyTransfer/out/obj/easytransfer.xpm] Error 1

**Comment by jamarju** [comment]
`convert` is part of the imagemagick package. Do:

`brew install imagemagick`

It's actually in the README under the [Cross dev tools... title](https://github.com/jamarju/easyflash#cross-dev-tools-and-ftdi-libs)

**Comment by jamarju** [comment]
Closing, please reopen if there's still any issue after closely following the directions and thanks for your feedback.

**Comment by UTilitieeees** [comment]
The trick was: brew install wxWidgets

**Comment by fortiko** [comment]
also, now with Ventura removing python2, this is the python3 compatible version for easyflash/EasyTransfer/make/bin2c.py

```
#!/usr/bin/env python3
import sys


if __name__ == '__main__':
    if len(sys.argv) == 4:
        if sys.argv[1] == '-':
            instream = sys.stdin
        else:
            instream = open(sys.argv[1],'rb')
        if sys.argv[2] == '-':
            outstream = sys.stdout
        else:
            outstream = open(sys.argv[2], 'wt')
        varname = sys.argv[3]
    else:
        print("Usage: bin2c infile outfile varname")
        sys.exit(0)

    outstream.write("\n\nconst unsigned char %s[] = {\n    " % varname)
    written = 0
    while True:
        byte = instream.read(1)
        if len(byte) != 1:
            break
        outstream.write( "0x%.2x, " % ord(byte) )
        written += 1
        if written % 16 == 0:
            outstream.write( "\n    " )
    outstream.write("\n};\n")
    outstream.write("\nint %s_size = %i;\n\n" % (varname, written))

    sys.exit(0)

**Comment by jamarju** [comment]
Thank you! Would you mind sending a PR and I'll merge it?
